print('¿Qué sale de la cruza entre un mono y un pato?')
input()
print('¡Un monopatin!')
print()
print('¿Porqué vuelan los pájaros pa\'l sur?')
input()
print('¡Porque caminando tardarian muchisimo!')
print()
print('Él se fue volando en un helicoptero verde\\turquesa')
print('¿En qué se parecen una familia, un bombero y un barco?')
input()
print("no sé... ¿en qué se parecen?")
input()
print('En que el bombero y el barco tienen casco.')
input()
print('¿Y la familia?', end='')
print(' -Bien. gracias.')