cadena = input("Digite la cadena de texto: ")
cadenamayus = cadena.upper()
print ("cadena en mayuscula " + cadenamayus)
cadenamin = cadena.lower()
print ("cadena en minusculas " + cadenamin)
primeramayus = cadena.title()
print ("la primera en mayuscula " + primeramayus) 